include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - lib/generated/**
    - plugins/**
  errors:
    missing_required_param: warning
    parameter_assignments: warning
    missing_return: error
    todo: ignore

dart_code_metrics:
  metrics:
    - cyclomatic-complexity: 20
    - halstead-volume: 150
    - lines-of-code: 100
    - maintainability-index: 50
    - maximum-nesting-level: 5
    - number-of-methods: 10
    - number-of-parameters: 6
    - source-lines-of-code: 50
    - technical-debt:
        threshold: 1
        todo-cost: 161
        ignore-cost: 320
        ignore-for-file-cost: 396
        as-dynamic-cost: 322
        deprecated-annotations-cost: 37
        file-nullsafety-migration-cost: 41
        unit-type: "USD"
    - weight-of-class: 0.33
  rules:
    # Common
    - avoid-collection-methods-with-unrelated-types
    - avoid-dynamic:
        exclude:
          - test/**
    - avoid-global-state
    - avoid-late-keyword:
        exclude:
          - test/**
          - lib/main.dart
    - avoid-missing-enum-constant-in-map
    - avoid-nested-conditional-expressions:
        acceptance-level: 2
    - avoid-non-null-assertion
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - binary-expression-operand-order
    - double-literal-format
    - format-comment
    - member-ordering:
      alphabetize: true
      order:
        - public-fields
        - private-fields
        - constructors
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-then-else
    - no-object-declaration
    - prefer-async-await
    - prefer-commenting-analyzer-ignores
    - prefer-conditional-expressions
    - prefer-correct-identifier-length:
        exceptions:
          - id
          - ok
          - i
    - prefer-correct-type-name:
        max-length: 44
    - prefer-first
    - prefer-last
    - prefer-immediate-return
    - prefer-match-file-name:
        exclude:
          - test/**
    - prefer-moving-to-variable:
        exclude:
          - test/**
    - prefer-trailing-comma
    # Flutter specific
    - always-remove-listener
    - avoid-border-all
    - avoid-returning-widgets
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - prefer-const-border-radius
    - prefer-extracting-callbacks
    - prefer-single-widget-per-file:
        ignore-private-widgets: true

  anti-patterns:
    - long-method
    - long-parameter-list

  metrics-exclude:
    - test/**
  rules-exclude:
    - test/**
