name: chattopic
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  intl_utils: ^2.6.1
  # Icons
  cupertino_icons: ^1.0.2
  collection: ^1.16.0
  shared_preferences: ^2.0.15
  bloc: ^8.0.3

dev_dependencies:
  dart_code_metrics: ^4.14.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  test: any

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/font/

  fonts:
    - family: NDS12
      fonts:
        - asset: assets/font/NDS12.ttf
          weight: 400

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: assets/l10n
  ouput_dir: lib/generated
